set(sources ${sources}
    src/plugin.cpp
    src/hook.cpp
    src/Config.cpp
    src/InputManager.cpp
    src/MenuChecker.cpp
    src/higgsinterface001.cpp
    src/projectile/Anchor.cpp
    src/projectile/FormManager.cpp
    src/projectile/GameProjectile.cpp
    src/projectile/ControlledProjectile.cpp
    src/projectile/ControlledLight.cpp
    src/projectile/TransformSmoother.cpp
    src/projectile/ProjectileSubsystem.cpp
    src/projectile/ProjectileHook.cpp
    src/projectile/ProjectileDriver.cpp
    src/projectile/TextAssets.cpp
    src/projectile/TextureManipulator.cpp
    src/projectile/AsyncTextureLoader.cpp
    src/projectile/Drivers/RadialProjectileDriver.cpp
    src/projectile/Drivers/HalfWheelProjectileDriver.cpp
    src/projectile/Drivers/ColumnGridProjectileDriver.cpp
    src/projectile/Drivers/RowGridProjectileDriver.cpp
    src/projectile/Drivers/CurvedRowProjectileDriver.cpp
    src/projectile/Drivers/GridProjectileDriver.cpp
    src/projectile/Drivers/TextDriver.cpp
    src/api/ThreeDUIInterface001Impl.cpp
    src/api/WrapperRegistry.cpp
    src/api/ElementWrapper.cpp
    src/api/TextWrapper.cpp
    src/api/ContainerWrappers.cpp
    src/api/RootWrapper.cpp
    src/api/ActorMenuImpl.cpp
    src/projectile/InteractionController.cpp
    src/projectile/DriverUpdateManager.cpp
    src/projectile/TooltipTextDisplayManager.cpp
    src/projectile/ProjectileCleanupManager.cpp
    src/util/Haptics.cpp
    src/util/HapticPulses.cpp
)
